#services:
#  db:
#    image: postgres:17
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#      start_period: 5s
#    volumes:
#      - db_data:/var/lib/postgresql/data
#  redis:
#    image: redis:7-alpine
#    container_name: url_shortener_redis
#    command: redis-server --appendonly yes --requirepass redis_password_123
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#    networks:
#      - shortener-network
#    healthcheck:
#      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5